---
resource_types:
- name: gcs-resource
  type: registry-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: netcore-source
  type: git
  source:
    uri: https://github.com/apache/geode-dotnet-core-client
    branch: develop
- name: aspnetcore-image
  type: registry-image
  icon: docker
  source:
    repository: mcr.microsoft.com/dotnet/sdk
    tag: "5.0"
#- name: package-windows-2019-vs-2019-debug-archive
#  icon: content-save
#  source:
#    bucket: apachegeode-ci-concourse
#    json_key: ((concourse-gcp-key))
#    regexp: geode-native/geode-native-develop/packages/windows-2019-vs-2019/debug/apache-geode-native-(?P<version>.*)-Windows-64bit.zip
#  type: gcs-resource
- name: package-ubuntu-20.0.4-debug-archive
  icon: content-save
  source:
    bucket: apachegeode-ci-concourse
    json_key: ((concourse-gcp-key))
    regexp: geode-native/geode-native-develop/packages/ubuntu-20.04/debug/apache-geode-native-(?P<version>.*)-Linux-64bit.tar.gz
  type: gcs-resource

jobs:
- name: aspnetcore-unit-tests
  plan:
  - in_parallel:
    - get: netcore-source
      trigger: true
    - get: aspnetcore-image
    - get: package-ubuntu-20.0.4-debug-archive
  - task: run-tests
    privileged: true
    image: aspnetcore-image
    config:
      platform: linux
      inputs:
      - name: netcore-source
      - name: package-ubuntu-20.0.4-debug-archive
      run:
          path: sh
          args:
          - -exc
          - |
              cd package-ubuntu-20.0.4-debug-archive
              tar xvf apache-geode-native-1.15.0-build.46-Linux-64bit.tar.gz
              # geode-native install now in apache-geode-native
              cd ..
              cd ./netcore-source
              dotnet restore
              dotnet test
